config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'articles#index'
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates_date :published_on, on_or_after: lambda { Date.current }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, except: [:index,:create,:new]

  def index
    @articles = Article.where("published_on <= ?", Date.current)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    respond_to do |format|
      if @article.save
        format.html { redirect_to articles_path, notice: 'Article was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to articles_path, notice: 'Article was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_path, notice: 'Article was successfully destroyed.' }
    end
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:name, :published_on, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div class="blog-post">
  <h2 class="blog-post-title"><%= article.name %></h2>
  <p class="blog-post-meta"><%= article.published_on %></p>
  <%= raw(article.content) %>
  <%= link_to "Edit", edit_article_path(article) %>
</div><!-- /.blog-post -->
<hr>

app/views/articles/_form.html.erb
<%= simple_form_for(@article) do |f| %>
<%= f.error_notification %>
  <div class="form-group">
    <div class="col-sm-10">
      <%= f.input :name, label: false, required: true, placeholder: "Name of the Article" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-10">
      <%= f.input :content, label: false, required: true, placeholder: "Please write using html" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-10">
      <%= f.input :published_on, label: false, required: true %>
    </div>
  </div>
  <div class="line line-dashed b-b line-lg pull-in"></div>
  <div class="form-group">
    <div class="col-sm-4">
      <%= link_to "Back", :back, class: "btn btn-default" %>
      <%= f.button :submit, class: "btn btn-info" %>
    </div>
  </div>
<% end %>

app/views/articles/edit.html.erb
<div class="blog-header">
  <h1 class="blog-title">Edit Post</h1>
</div>
<div class="row">
  <div class="col-sm-8 blog-main">
    <%= render "form" %>
  </div>
</div>

app/views/articles/index.html.erb
<div class="blog-header">
  <h1 class="blog-title">The Codeplace Blog</h1>
  <p class="lead blog-description">Where great software stories are told</p>
</div>

<div class="row">

  <div class="col-sm-8 blog-main">
    <%= render @articles %>
  </div><!-- /.blog-main -->
</div><!-- /.row -->

app/views/articles/new.html.erb
<div class="blog-header">
  <h1 class="blog-title">New Post</h1>
</div>
<div class="row">
  <div class="col-sm-8 blog-main">
    <%= render "form" %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Codeplace Blog", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "New Article", new_article_path %></li>
        <li><%= link_to "Articles", articles_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codeplace Blog V1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>